### ISSUE TITLE
Add support for hexadecimal string literals

### ISSUE THREAD

**Issue by federicobond** [ConsenSys/solidity-parser#16]
Syntax is `hex"ab1248fe"`

**Comment by tcoulter** [comment]
Which version of the solidity parser are you using? Support for hexadecimal strings was added in 0.1.1 - https://github.com/ConsenSys/solidity-parser/commit/9159f9e92307e65bd32a84f9fc7043d745d92f5d

Closing this ticket. Please update to 0.1.1 and reopen with a code example if they still aren't working for you. Thanks!

**Comment by federicobond** [comment]
My bad, I had cloned the latest master but made that test with a version installed as dependency of another project.
