### ISSUE TITLE
Separate top-level statements in grammar

### ISSUE THREAD

**Issue by federicobond** [ConsenSys/solidity-parser#17]
Right now, the grammar allows pragma directives, imports and contracts to be declared inside the contract. These should trigger a syntax error:

```                                                                                                                                          
contract MyContract {
    function() {
        pragma solidity ^0.4.4;
    }
}
```

```                                                                                                                                          
contract MyContract {
    function() {
        contract OtherContract {

        }
    }
}
```

The `solc` compiler grammar singles these out in the `SourceUnit` rule. See [here](https://github.com/ethereum/solidity/blob/d3f410d8a89aaa042ff264d7a0ea79184e01abab/libsolidity/grammar.txt#L1).

**Comment by duaraghav8** [comment]
I'm not that experienced with PegJs so don't mind my being naive, but wouldn't this become significantly more complex? To specify **which nodes are allowed inside** for every node?

**Comment by federicobond** [comment]
It shouldn't be difficult, just a matter of separating that big statement list into two rules.
