### ISSUE TITLE
Array constructor rule

### ISSUE THREAD

**Issue by cgewecke** [ConsenSys/solidity-parser#43]
As @federicobond observed in #40 - fixing #29 (parse memory array allocation) by letting an expression between array brackets be optional is too permissive because 
```
function test() {
    uint[] memory a = new uint[](7);
    a[];
  }
```
now parses without complaining about `a[]`. Array constructors need their own rule.

**Comment by frangio** [comment]
Also note that `uint[]` in `new uint[](7)` is parsed as a `MemberExpression` instead of a type.
