### ISSUE TITLE
Merge in changes from duaraghav8/solparse

### ISSUE THREAD

**Issue by axic** [ConsenSys/solidity-parser#6]
Would it be possible to have a single project for AST parsing?

cc @tcoulter @duaraghav8

**Comment by duaraghav8** [comment]
@axic I guess this repo is not being actively maintained (which is the reason I created solparse). However, I'd be happy to merge if ConsenSys team is interested.

**Comment by tcoulter** [comment]
This project is being maintained so long as features are needed, and it's used activelyin Truffle 2.0.

@axic Which project should this go into (or should merge with this)?

**Comment by tcoulter** [comment]
Ah, I didn't read the title. I'll check it out

**Comment by tcoulter** [comment]
@duaraghav8 I'd be happy to merge those changes. Somehow I missed your PR, which you submitted two weeks ago. I'll add the merge of your whole fork into my list of current tasks. I appreciate your help. Thanks @axic for bringing this to my attention. @duarghav8, apologies for not seeing your initial PR.

**Comment by duaraghav8** [comment]
@tcoulter That's great! The only changes made are in ```solidity.pegjs``` and ```build/parser.js```.
I created my fork primarily so I could quickly push code and make releases, since 4 of my projects are now (heavily) dependant on solidity parser.

Please let me know if you require anything from my side.

**Comment by tcoulter** [comment]
Sorry for the lateness on this. Your fork has been merged into the master branch. I added some code to the parsing examples to cover the bugs that you fixed. I didn't keep the rename of `solidity-parser.pegjs`, however (mostly a stylistic preference, though open to the rename if there's a better reason). 

Just to better communicate the situation: I maintain Truffle, ethereumjs-testrpc, solidity-parser and EtherPudding (among other things) as a one-man team. Though it may take me a bit to get to PR's, I'm **very** happy to receive them and I very much love the participation. In the future, definitely submit more PRs for all your fixes (I know you tried with one, but it took me awhile to get to). I really appreciate it.

Thanks again!

**Comment by tcoulter** [comment]
@duaraghav8 FYI: solidity-parser 0.1.0 released. Also, I kept you in the list of authors in package.json. Thanks again.

**Comment by duaraghav8** [comment]
Awesome! Nope, keeping the same name is fine.
Sure, I will be submitting issues & PRs soon, since a couple of people have raised solidity-parser related issues on my repos (my projects rely on this module).

**Comment by tcoulter** [comment]
👏
