### ISSUE TITLE
Support for Interfaces

### ISSUE THREAD

**Issue by marekkirejczyk** [ConsenSys/solidity-parser#67]
With new version of solidity (0.4.11) we have now support for interfaces.

Currently if you add following code to contract source:
```
interface i {
  function f();
}
```

Parser will fail to parse it. E.g if you add this code to solidity parser tests it will result in following error:
```
     Expected "contract", "import", "library", "pragma", comment, end of input, end of line, or whitespace but "i" found. Line: 19, Column: 1
  SyntaxError: Expected "contract", "import", "library", "pragma", comment, end of input, end of line, or whitespace but "i" found.
      at peg$buildStructuredError (build/parser.js:1272:12)
      at Object.peg$parse [as parse] (build/parser.js:13877:11)
      at Object.parse (index.js:34:23)
      at Object.parseFile (index.js:45:17)
      at Context.<anonymous> (test/general.js:15:20)
```

This makes it impossible to use interfaces with Truffle.

**Comment by marekkirejczyk** [comment]
Added a pull request fixing the issue.

**Comment by marekkirejczyk** [comment]
btw is there any release planned anytime soon? :)

**Comment by federicobond** [comment]
pinging @tcoulter to cut a new release

**Comment by robert-zaremba** [comment]
Is it already released? Truffle still can't handle `interface`.

**Comment by paulofelipe84** [comment]
Any news about the release?

**Comment by Nehaw149** [comment]
Hi Guys, can somebody mention if it's released?
