### ISSUE TITLE
Struct instantiation pattern "MyStruct ({...})" doesn't get parsed

### ISSUE THREAD

**Issue by duaraghav8** [ConsenSys/solidity-parser#76]
According to solidity [struct](http://solidity.readthedocs.io/en/develop/types.html#structs) doc, this should get compiled:

```
contract foo {
  struct fs { uint x; }
  function b () {
    if (true)
      fs ({ x: 100 });
  }
}
```
(compiles in solc)

However, SP throws a parse error
```
Error: An error occured while parsing the source code:
SyntaxError: Expected "!", "!=", "(", ")", "+", "++", "-", "--", "0", "<", "<=", "==", ">", ">=", "[", "^", "delete", "false", "hex", "mapping", "new", "this", "true", "v", "~", [1-9], comment, end of line, identifier, number, string, or whitespace but "{" found.
```

this is because it doesn't recognise patterns like:
```
foo ({ x: 100 });
```

where foo is:

```
struct foo {
  uint x;
}
```

**Comment by cgewecke** [comment]
Hi @duaraghav8! Are you using latest master? Rules to parse these cases were added only very recently. Are you going to try plug SP into Solium?

**Comment by duaraghav8** [comment]
@cgewecke let me update my module and re-try. I AM currently working on moving to SP and deprecating solparse

**Comment by duaraghav8** [comment]
it works in 0.3.0, my bad :)

**Comment by duaraghav8** [comment]
@cgewecke IDK I might be doing something stupid here, but I still can't get it to work.

![screen shot 2017-06-16 at 1 42 12 pm](https://user-images.githubusercontent.com/12758282/27218065-301536c2-529a-11e7-936e-2da5c79bcee2.png)

when I remove the ```{ x: 100 }``` from inside ```fs ()```, it gets parsed with no trouble.

using latest version
![screen shot 2017-06-16 at 1 44 36 pm](https://user-images.githubusercontent.com/12758282/27218084-543d0b60-529a-11e7-8835-cd65346c6a19.png)


Can you please use the below code and see if SP parses it without any problems for you?
```
contract foo {\n  struct fs { uint x; }\n  function b () {\n    if (true) fs ({ x: 100 });\n  }\n}\n
```

**Comment by cgewecke** [comment]
@duaraghav8 I'm sorry I should have been clearer above - these changes are in master but haven't been published to npm yet. That segment should parse when the version gets bumped. . .

**Comment by duaraghav8** [comment]
oh cool. Just let me know when you guys are planning to make the next release.
