### ISSUE TITLE
Also build parser on postinstall?

### ISSUE THREAD

**Issue by cgewecke** [ConsenSys/solidity-parser#77]
@frangio added this nice build script in  #64 - initially he used the `prepare` hook but because that's so new it was changed to `prepublish`. 

This works well for CI and publishing to npm but if you try to install SP as a dependency from the git repo in order to have access to the latest changes, the built parser isn't there.  [This issue](https://github.com/npm/npm/issues/3055) at npm describes the problem. 

It looks like having a `postinstall` hook would make it possible to install successfully from the repo, Does anyone have any views about this?

**Comment by elenadimitrova** [comment]
In fact it doesn't work well in CI when using `yarn`, see comment to #64   https://github.com/ConsenSys/solidity-parser/pull/64#issuecomment-311887116

**Comment by cgewecke** [comment]
Thanks @elenadimitrova! Good to know.
