### ISSUE TITLE
Add "build" to .gitignore

### ISSUE THREAD

**Issue by duaraghav8** [ConsenSys/solidity-parser#84]
Devs have to make sure their build/ directory doesn't get included on to version control every time they want to commit after testing their changes.
Makes sense for us to add ```build``` to ```.gitignore```.

**Comment by federicobond** [comment]
Good idea! Note that you can also add `build/` to your `.git/info/exclude` file and ignore those files in your local clone.

**Comment by duaraghav8** [comment]
UPDATE: Just figured, adding build/ to .gitignore messes things up, because the build directory doesn't get published on NPM, so when you install SP on your machine you end up without the build/ dir & the parsing js files.

Will try the ```.git/info/exclude``` method though
