### ISSUE TITLE
Errors when ReturnStatement arguments are on subsequent lines 

### ISSUE THREAD

**Issue by cgewecke** [ConsenSys/solidity-parser#86]
SP errors this:
```
contract multilineReturn {
  function a() returns (uint x) {
    return
      5;
  }
}
```
Compiles fine though. An example from the wild can be seen at Numerai [here](https://github.com/numerai/contract/blob/master/contracts/NumeraireShared.sol#L63). 
Opening a PR in a second.

**Comment by federicobond** [comment]
Yes, another remnant of the ECMAScript syntax this parser was based on. Should be a single character fix :)
