### ISSUE TITLE
Need support for 'var (x, y)'

### ISSUE THREAD

**Issue by duaraghav8** [ConsenSys/solidity-parser#9]
Originally reported by 4gn3s

Following code

``` js
var (x, y) = (10, 20)
```

is legal in Solidity, but not yet parsed by SP.
Though it recognises `(10, 20)` as `SequenceExpression`, `var (x, y)` causes parsing error.

Will be making a PR for this soon.

**Comment by raineorshine** [comment]
Yup, ran into this, too (with the help of @nicksavers). Somewhere around here: https://github.com/ConsenSys/solidity-parser/blob/master/solidity.pegjs#L1123-L1142

**Comment by duaraghav8** [comment]
@raineorshine I've implemented this feature on my fork (npm install solparse) and am trying to get solidity devs to test it. Once I'm satisfied, I'll push the changes here.
If you find time, do test it out and let me know in case improvements need to be made

Samples of statements I've been testing out:
```var (x, y, x) = (10, "Hello world", 9028.2897);```
```var (x, y, x) = getMyTuple ();```

**Comment by raineorshine** [comment]
Awesome, thanks!

**Comment by cgewecke** [comment]
@duaraghav8  Do you have any interest in submitting a PR to SP for this?

**Comment by duaraghav8** [comment]
ok so currently something like:

```js
var (x, y) = (10, 20)
```
gets parsed into:

```js
{
  "type": "VariableDeclarationTuple",
  "declarations": [
    {
      "type": "VariableDeclarator",
      "id": {
        "type": "Identifier",
        "name": "x",
        "start": 5,
        "end": 6
      },
      "init": null,
      "start": 5,
      "end": 6
    },
    {
      "type": "VariableDeclarator",
      "id": {
        "type": "Identifier",
        "name": "y",
        "start": 7,
        "end": 8
      },
      "init": null,
      "start": 7,
      "end": 8
    }
  ],
  "init": {
    "type": "SequenceExpression",
    "expressions": [
      {
        "type": "Literal",
        "value": 10,
        "start": 13,
        "end": 15
      },
      {
        "type": "Literal",
        "value": 20,
        "start": 17,
        "end": 19
      }
    ]
  },
  "start": 0,
  "end": 20
}
```

I'd like opinions on this before I push, @federicobond @tcoulter @raineorshine @cgewecke 

@cgewecke as you mentioned [here](https://github.com/ConsenSys/solidity-parser/pull/44#issuecomment-270479159), could you tell me why the current code is still a crasher?

**Comment by cgewecke** [comment]
Oh I'm so sorry - I made an inference about the [solcover issue](https://github.com/JoinColony/solcover/issues/25) referenced above and saw this was still open but I don't actually know what the problem is. Is this issue closable? 

@area do you know if issues with tuples / sequences definitely originate in the parser?

**Comment by cgewecke** [comment]
@duaraghav8 SP still errors on the comma after `x`, expecting a close paren.
```
var(x,y) = (10,20);
```
So you would open a PR that adds the variable tuple parsing. . . basically from your [line 1160](https://github.com/duaraghav8/solparse/blob/master/solidity-parser.pegjs#L1160) to your [line 1187](https://github.com/duaraghav8/solparse/blob/master/solidity-parser.pegjs#L1187). One difference is that the 'noInit' rules have been [removed from SP recently](https://github.com/ConsenSys/solidity-parser/commit/d545849069eaa2134bfc8dbd5f7dc232d1f8ec36). Are those required for your implementation to work?
