### ISSUE TITLE
Parser fails when it reaches a symbol with name "export"

### ISSUE THREAD

**Issue by bitsandsalsa** [ConsenSys/solidity-parser#95]
Tested on v0.4.0. Here is a Solidity test case:

`contract export {}`

**Comment by duaraghav8** [comment]
the parser has reserved some words like `export` in anticipation that they'll be part of solidity grammar in future.
If you want to make changes to your own fork, see this commit that I made to my parser
https://github.com/duaraghav8/solparse/commit/329f396f4ae09ead50dfbb90942623e2ce163f28

I recommend you change your contract's name (maybe slightly)
or switch to federicobond's antlr parser if you can afford the API change
