### ISSUE TITLE
How to get contract address in web3

### ISSUE THREAD

**Issue by tbenny** [ConsenSys/solidity-parser#99]
var Web3 = require("web3");
            var web3 = new Web3();
            var ethlog = web3.setProvider(new web3.providers.HttpProvider("http://localhost:8545/"));
         
            var  ContractABI = [{"constant":true,"inputs":[{"name":"_parent","type":"address"},{"name":"register","type":"address[]"}],"name":"isNotDuplicateChild","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"pure","type":"function"},{"constant":true,"inputs":[{"name":"_address","type":"address"}]}];
            var RegContract = web3.eth.contract(  RegContractABI);
            console.log(RegContract.address);
            var  Reg = RegContract.at("Contract Address");

How to get the Contract adress?

**Comment by federicobond** [comment]
Hi @tbenny, please ask this on StackOverflow or the web3.js repo. This is for the Solidity source code parser only.
